name: Deploy FastAPI Model

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build Docker Image
        run: docker build -t fastapi-app .

      - name: Run Container Locally
        run: |
          docker run -d --name fastapi-container -p 7500:7500 fastapi-app
          sleep 10  # Ensure server has time to start

      - name: Wait for FastAPI to Start
        run: |
          echo "Waiting for FastAPI to become available..."
          for i in {1..10}; do
            curl --silent --fail http://127.0.0.1:7500/docs && break
            echo "FastAPI not ready yet... retrying in 2s"
            sleep 2
          done

      - name: Run Unit Tests
        run: |
          pip install requests
          python -m unittest discover tests  # Run all tests in `tests/`

      - name: Print FastAPI Logs if Tests Fail
        if: failure()
        run: |
          echo "FastAPI logs:"
          docker logs fastapi-container
